name: Fetch User Events

on:
  schedule:
    - cron: '0 * * * *'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  fetch_user_events:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch User Events
      uses: actions/github-script@0.7.0
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
      with:
        script: |
          const octokit = require("@octokit/rest")();
          octokit.authenticate({
            type: "token",
            token: process.env.GITHUB_TOKEN,
          });

          const query = `
            query {
              viewer {
                events(first: 100) {
                  nodes {
                    id
                    createdAt
                    type
                  }
                }
              }
            }
          `;

          octokit.graphql(query).then((result) => {
            console.log("User events:", result.viewer.events.nodes);
          });
